"use client";
import localFont from "next/font/local";
// import "./globals.css";
// import Navbar from "./navbar";
import { Toaster } from "react-hot-toast";
import Sidebar from "./sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "DIY-Where Everyone is a Creator",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div></div>
        <div className="">
          {/* Sidebar (Fixed Width) */}
          <Sidebar />

          {/* Main Content (Takes Remaining Space) */}
          <div className="">{children}</div>
        </div>

        <Toaster>
          {(t) => (
            <ToastBar
              toast={t}
              style={{
                ...t.style,
                animation: t.visible
                  ? "custom-enter 1s ease"
                  : "custom-exit 1s ease",
              }}
            />
          )}
        </Toaster>
      </body>
    </html>
  );
}

